version=0.1
[default.global.parameters]
region="us-east-1"
[default.deploy]
[default.deploy.parameters]
stack_name = "j-groups"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-kgz59zry9vyv"
s3_prefix = "j-groups"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
disable_rollback = false
image_repositories = []
